services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  webserver:
    build:
      dockerfile: build/webserver.Dockerfile
      context: .
      tags: ["ghcr.io/ryan-willis/qotd:latest"]
    environment:
      - REDIS_HOST=redis:6379
    ports:
      - "9076:9075"
    depends_on:
      - redis
